config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', :locale => /en/ do
    root 'posts#index'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    post 'forgot_password_create', to: 'sessions#forgot_password_create'
    post 'new_password_create', to: 'sessions#new_password_create'
    get 'confirm_email', to: 'users#confirm_email'
    get 'users', to: 'users#index'
    post 'users/update_role/:id', to: 'users#update_role', as: :update_role
    post 'users/', to: 'users#create'
    get '/oauth2callback' => 'events#callback'

    resources :users do
      post   'update_avatar'
      collection do
        get   'profile'
        get   'password'
        post  'update'
        post  'update_profile'
        post  'change_password'
      end
    end

    resources :posts do
      member do
        get 'up', to: 'posts#up'
        get 'down', to: 'posts#down'
      end
      collection do
        post 'update_result'
        get 'new_vote'
        get 'new_randomize'
        get 'votes', to: 'posts#index', defaults: { type: Post::TYPE_VOTE }
        get 'randomizes', to: 'posts#index', defaults: { type: Post::TYPE_RANDOM }
      end
    end

    resources :posts
    resource :events

  end

  # Mobile APIs
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :public do
        post   'auth_code'  => 'session#auth_code'
        post   'api_token'  => 'session#api_token'
        post   'sign_out'   => 'session#sign_out'
      end

      resources :posts do
        get 'up'
        get 'down'
        get 'update_random' => 'posts#update_random'
        collection do
          post 'update_result'
          get 'new_vote'
          get 'new_randomize' => 'posts#update_random'
          get 'votes', to: 'posts#index', defaults: { type: Post::TYPE_VOTE }
          get 'randomizes', to: 'posts#index', defaults: { type: Post::TYPE_RANDOM }
        end
      end
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  after_initialize :set_default_role, if: :new_record?

  scope :login_today, -> { where('last_login_time > ? and last_login_time < ?', Date.today, Date.tomorrow) }

  enum role: [:user, :leader, :admin]

  validates :email,
            uniqueness: true
  validates :name,
            uniqueness: {case_sensitive: false}

  def set_default_role
    self.role ||= :user
  end

  def get_avatar_path
    image_url.nil? || image_url.empty? ? "/images/team_logo.png" : image_url
  end

  def is_changing_password=(value)
    @is_changing_password = value
  end

  def is_changing_password?
    @is_changing_password
  end

  def self.search(keywords)
    if keywords.present?
      condition = User.arel_table[:name].eq(keywords)
      keywords.split(' ').each do |keyword|
        condition = condition.or(User.arel_table[:name].        matches("%#{keyword}%"))
        condition = condition.or(User.arel_table[:email].       matches("%#{keyword}%"))
      end
      all.where(condition)
    else
      all
    end
  end

  def secure_password
    result = true
    result = false if (password =~ /[a-z]/).blank? #lower letter test
    result = false if (password =~ /[A-Z]/).blank? #upper letter test
    result = false if (password =~ /[0-9]/).blank? #number test
    result = false if password.present? && password.size < 6
    if !result
      errors.add(:base, 'Password should be contains at least')
      errors.add(:base, '1 lower letter')
      errors.add(:base, '1 upper letter')
      errors.add(:base, '1 digit letter')
      errors.add(:base, 'the length greater than 5 letters')
    end
    return result
  end

  def self.get_avatar_path_by_id (user_id)
    user = User.find(user_id)
    user.get_avatar_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:create]
  before_action :init_user, only: [:show, :edit, :update, :change_password, :destroy, :update_role, :create]

  def update_avatar
    user    = User.find_by(id: params[:user][:id])
    update_params = user_params
    if params[:user][:avatar]

      # Option for uploading to Imgur
      # See ref: https://api.imgur.com/endpoints/image
      options = {}
      options[:image]  = params[:user][:avatar]
      options[:title] = user.id
      options[:description] = user.name
      options[:album_id] = ENV['IMGUR_ALBUM_ID']
      imgur_image = Imgur::Image.create(options)
      update_params[:image_id] = imgur_image['id']
      update_params[:image_url] = imgur_image['link']

      # For 3S AWS. No use now.
      # avatar  = params[:user][:avatar]
      # image = Image.new
      # image.temp_path = "/temp/#{avatar.original_filename}"
      # FileStore.bucket.put_object(key: image.temp_path, body: avatar, acl: 'public-read')
      # image.save
      # update_params[:image_id] = image.id
    end

    if user.update(update_params)
      redirect_to users_path
    else
      flash.now[:error] = 'Something wrong! Please recheck your photo'
      redirect_to edit_user_path
    end
  end

  # GET /users
  def index
    authorize @current_user
    @users = User.all.order(:id)
    if params[:keyword]
      @users = @users.search(params[:keyword])
    else
      @users
    end
  end

  # GET /users/1
  def show
    render :edit
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    if current_user.admin?
      @user = User.new(user_params)
      if @user.save
        flash.now[:notice] = 'Welcome onboard!'
        redirect_to users_path
      else
        flash.now[:error] = 'Something bad happened! Are you a guru?'
        redirect_to new_user_path
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      flash.now[:notice] = "Hey #{@user.name}! You've changed your info, any dark work?"
      flash.keep
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  def update_role
    begin
      if @user.update(user_params)
        flash.now[:notice] = "#{@user.name}'s role is updated!"
        flash.keep
        redirect_to users_path
      else
        flash.now[:error] = 'Something bad happened! Are you a guru?'
        flash.keep
        redirect_to users_path
      end
    rescue StandardError
      redirect_to users_path
    end
  end

  # DELETE /users/1
  def destroy
    flash.now[:notice] = "Goodbye #{@user.name}. You broke our heart!"
    flash.keep
    @user.destroy
    redirect_to users_url
  end

  # POST /update_profile
  def update_profile
    if @current_user.update(profile_params)
      flash.now[:notice] = "Hey #{@user.name}! You've changed your info, any dark work?"
      flash.keep
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  # POST /change_password
  def change_password
    current_user.is_changing_password = true

    flash.now[:error] = 'Sometimes, gurus forget their password.' unless current_user.authenticate params[:current_password]
    flash.now[:error] = 'Gurus don\'t leave password empty'       unless params[:password].present?
    flash.now[:error] = 'Gurus don\'t misstype password'          unless params[:password] == params[:password_confirmation]
    if flash.now[:error].any?
      flash.keep
      redirect_to edit_user_path(@user)
      return
    end

    if @user.update(change_password_params)
      flash.now[:notice] = 'That\'s why we call you guru! Easy job right?'
    else
      flash.now[:error] = 'Cannot update, guru'
    end

    flash.keep
    redirect_to edit_user_path(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def init_user
      @user = User.find_by_id(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(
        :name, 
        :email,
        :password,
        :role,
        :image_id
      )
    end

    def role_params
      params.require(:user).permit(
          :role
      )
    end
    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:user).permit(
          :name
      )
    end

    # Only allow a trusted parameter "white list" through.
    def change_password_params
      params.permit(
          :password,
          :password_confirmation,
      )
    end

    def update_avatar_params
      params.require(:user).permit(
          :id,
          :avatar
      )
    end
end

app/views/users/_change_password_form.html.haml
= form_tag change_password_users_path, id: 'frmUserChangePassword', :autocomplete => 'off', :method => 'post' do
  = hidden_field_tag 'id', @user[:id]
  .form-group
    %label.control-label Current Password
    = password_field_tag :current_password, '', class: 'form-control', placeholder: 'Current Password', autocomplete: false
  .form-group
    %label.control-label New Password
    = password_field_tag :password, '', class: 'form-control', placeholder: 'New Password'
  .form-group
    %label.control-label Re-type New Password
    = password_field_tag :password_confirmation, '', class: 'form-control', placeholder: 'Re-type New Password'
  .margin-top-10
    %button.btn.green{:type => "submit"} Change Password
    %a.btn.default{:href => "javascript:;"} Cancel

app/views/users/_sign_up_form.html.haml
=form_for @user, url: {controller: 'users', action: 'create'}, method: 'post', html: {class: 'register-form'} do |f|
  .form-group
    %label.control-label.visible-ie8.visible-ie9 Avatar
    %div
      %div
        %div
          = image_tag "/images/team_logo.png", class: "img img-responsive", id: "avatar_img"
          = f.hidden_field :id
          = f.file_field :avatar, class: "upload", id: "avatar"
  .form-group
    %label.control-label.visible-ie8.visible-ie9 Name
    .input-icon
      %i.fa.fa-font
      = f.text_field :name, class: 'form-control placeholder-no-fix', placeholder: 'Name', type: 'text'
  %p Enter your account details below:
  .form-group
    %label.control-label.visible-ie8.visible-ie9 Email
    .input-icon
      %i.fa.fa-envelope
      = f.text_field :email, class: 'form-control placeholder-no-fix', placeholder: 'Email', type: 'text'
  .form-group
    %label.control-label.visible-ie8.visible-ie9 Password
    .input-icon
      %i.fa.fa-lock
      = f.text_field :password, class: 'form-control placeholder-no-fix', placeholder: 'Password', type: 'password'
  .form-group
    %label.control-label.visible-ie8.visible-ie9 Re-type Your Password
    .controls
      .input-icon
        %i.fa.fa-check
        %input.form-control.placeholder-no-fix{:autocomplete => "off", :name => "rpassword", :placeholder => "Re-type Your Password", :type => "password"}/
  .form-actions
    = link_to "Back", users_path, class: "btn red btn-outline", :type => "button"
    %button#register-submit-btn.btn.green.pull-right{:type => "submit"} Sign Up
    %button#register-submit-btn.btn.green.pull-right{:type => "submit"} Sign Up

app/views/users/_update_form.html.haml
=form_for @user, url: {controller: 'users', action: 'update'} do |f|
  .form-group
    %label.control-label Full Name
    = f.text_field :name, class: 'form-control', placeholder: 'Full Name', type: 'text'
  .form-group
    %label.control-label Email
    = f.text_field :email, class: 'form-control', placeholder: 'Email', type: 'text'
  .margiv-top-10
    %button.btn.green{:type => "submit"} Save Changes
    %a.btn.default{:href => "javascript:;"} Cancel

app/views/users/edit.html.haml
%div.page-content-wrapper
  %div.page-content
    %h3.page-title
      = "#{@user.name}'s profile"
    .row
      .col-md-12
        .profile-sidebar
          / PORTLET MAIN
          .portlet.light.profile-sidebar-portlet
            / SIDEBAR USERPIC
            .profile-userpic
              = image_tag @user.get_avatar_path, class: "img img-responsive"
            / END SIDEBAR USERPIC
            / SIDEBAR USER TITLE
            = form_for @user, url: user_update_avatar_path(@user), method: :post  do |f|
              = f.hidden_field :id

              = f.file_field :avatar, class: "upload_btn"

              .overlay-layer.col-lg-12.margin-horizontal-5 Upload Photo
              %br
              %button.btn.btn-outline{:type => "submit", :style => "text-align:center;margin-left:120px"} Save
            .profile-usertitle
              .profile-usertitle-name
                = @user.name
              .profile-usertitle-job
                A Guru
                %br

            / END SIDEBAR USER TITLE
            / SIDEBAR BUTTONS
            -#.profile-userbuttons
            -#  %button.btn.btn-circle.green.btn-sm{:type => "button"} Follow
            -#  %button.btn.btn-circle.red.btn-sm{:type => "button"} Message
            / END SIDEBAR BUTTONS
            / SIDEBAR MENU
            -#.profile-usermenu
            -#  %ul.nav
            -#    %li
            -#      %a{:href => "page_user_profile_1.html"}
            -#        %i.icon-home
            -#        Overview
            -#    %li.active
            -#      %a{:href => "page_user_profile_1_account.html"}
            -#        %i.icon-settings
            -#        Account Settings
            -#    %li
            -#      %a{:href => "page_user_profile_1_help.html"}
            -#        %i.icon-info
            -#        Help
          -#.portlet.light
            / STAT
            -#.row.list-separated.profile-stat
            -#  .col-md-4.col-sm-4.col-xs-6
            -#    .uppercase.profile-stat-title 37
            -#    .uppercase.profile-stat-text Projects
            -#  .col-md-4.col-sm-4.col-xs-6
            -#    .uppercase.profile-stat-title 51
            -#    .uppercase.profile-stat-text Tasks
            -#  .col-md-4.col-sm-4.col-xs-6
            -#    .uppercase.profile-stat-title 61
            -#    .uppercase.profile-stat-text Uploads
            / END STAT
            -#%div
            -#  %h4.profile-desc-title About Marcus Doe
            -#  %span.profile-desc-text Lorem ipsum dolor sit amet diam nonummy nibh dolore.
            -#  .margin-top-20.profile-desc-link
            -#    %i.fa.fa-globe
            -#    %a{:href => "http://www.keenthemes.com"} www.keenthemes.com
            -#  .margin-top-20.profile-desc-link
            -#    %i.fa.fa-twitter
            -#    %a{:href => "http://www.twitter.com/keenthemes/"} @keenthemes
            -#  .margin-top-20.profile-desc-link
            -#    %i.fa.fa-facebook
            -#    %a{:href => "http://www.facebook.com/keenthemes/"} keenthemes
        .profile-content
          .row
            .col-md-12
              .portlet.light
                .portlet-title.tabbable-line
                  .caption.caption-md
                    %i.icon-globe.theme-font.hide
                    %span.caption-subject.font-blue-madison.bold.uppercase Profile Account
                  %ul.nav.nav-tabs
                    %li.active
                      %a{"data-toggle" => "tab", :href => "#tab_1_3"} Change Password
                .portlet-body
                  .tab-content
                    - if flash[:error].present?
                      .alert.alert-danger.display-show
                        %button.close{"data-close" => "alert"}
                        %span
                          = flash[:error]
                    - if flash[:notice].present?
                      .alert.alert-success.display-show
                        %button.close{"data-close" => "alert"}
                        %span
                          = flash[:notice]
                    -##tab_1_1.tab-pane.active
                    -#  = render "update_form"
                    -##tab_1_2.tab-pane
                    -#  %p
                    -#    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum
                    -#    eiusmod.
                    -#  %form{:action => "#", :role => "form"}
                    -#    .form-group
                    -#      .fileinput.fileinput-new{"data-provides" => "fileinput"}
                    -#        .fileinput-new.thumbnail{:style => "width: 200px; height: 150px;"}
                    -#          %img{:alt => "", :src => "http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image"}
                    -#        .fileinput-preview.fileinput-exists.thumbnail{:style => "max-width: 200px; max-height: 150px;"}
                    -#        %div
                    -#          %span.btn.default.btn-file
                    -#            %span.fileinput-new Select image
                    -#            %span.fileinput-exists Change
                    -#            %input{:name => "...", :type => "file"}
                    -#          %a.btn.default.fileinput-exists{"data-dismiss" => "fileinput", :href => "javascript:;"} Remove
                    -#      .clearfix.margin-top-10
                    -#        %span.label.label-danger NOTE!
                    -#        %span Attached image thumbnail is supported in Latest Firefox, Chrome, Opera, Safari and Internet Explorer 10 only
                    -#    .margin-top-10
                    -#      %a.btn.green{:href => "javascript:;"} Submit
                    -#      %a.btn.default{:href => "javascript:;"} Cancel
                    / END CHANGE AVATAR TAB
                    / CHANGE PASSWORD TAB
                    #tab_1_3.tab-pane.active
                      = render "change_password_form"
                    / END CHANGE PASSWORD TAB
                    / PRIVACY SETTINGS TAB
                    #tab_1_4.tab-pane
                      %form{:action => "#"}
                        -#%table.table.table-light.table-hover
                        -#  %tr
                        -#    %td Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus..
                        -#    %td
                        -#      .mt-radio-inline
                        -#        %label.mt-radio
                        -#          %input{:name => "optionsRadios1", :type => "radio", :value => "option1"}/
                        -#          Yes
                        -#          %span
                        -#        %label.mt-radio
                        -#          %input{:checked => "", :name => "optionsRadios1", :type => "radio", :value => "option2"}/
                        -#          No
                        -#          %span
                        -#  %tr
                        -#    %td Enim eiusmod high life accusamus terry richardson ad squid wolf moon
                        -#    %td
                        -#      .mt-radio-inline
                        -#        %label.mt-radio
                        -#          %input{:name => "optionsRadios11", :type => "radio", :value => "option1"}/
                        -#          Yes
                        -#          %span
                        -#        %label.mt-radio
                        -#          %input{:checked => "", :name => "optionsRadios11", :type => "radio", :value => "option2"}/
                        -#          No
                        -#          %span
                        -#  %tr
                        -#    %td Enim eiusmod high life accusamus terry richardson ad squid wolf moon
                        -#    %td
                        -#      .mt-radio-inline
                        -#        %label.mt-radio
                        -#          %input{:name => "optionsRadios21", :type => "radio", :value => "option1"}/
                        -#          Yes
                        -#          %span
                        -#        %label.mt-radio
                        -#          %input{:checked => "", :name => "optionsRadios21", :type => "radio", :value => "option2"}/
                        -#          No
                        -#          %span
                        -#  %tr
                        -#    %td Enim eiusmod high life accusamus terry richardson ad squid wolf moon
                        -#    %td
                        -#      .mt-radio-inline
                        -#        %label.mt-radio
                        -#          %input{:name => "optionsRadios31", :type => "radio", :value => "option1"}/
                        -#          Yes
                        -#          %span
                        -#        %label.mt-radio
                        -#          %input{:checked => "", :name => "optionsRadios31", :type => "radio", :value => "option2"}/
                        -#          No
                        -#          %span
                        / end profile-settings
                        -#.margin-top-10
                        -#  %a.btn.red{:href => "javascript:;"} Save Changes
                        -#  %a.btn.default{:href => "javascript:;"} Cancel

app/views/users/index.html.haml
%div.page-content-wrapper
  %div.page-content
    %h3.page-title
      User management
    %div.row
      %div.col-md-12
        %div.portlet.light.some(style="float: left;")
          %div.portlet-title
            %div.caption.pull-left
              %i.icon-social-dribbble.font-green
              %span.caption-subject.font-green.bold.uppercase
                Users
            - if current_user.admin?
              .pull-right
                = link_to "New User", new_user_path, class: "btn btn-primary pull-right"
          .portlet-body.form.form-horizontal.form-bordered.form-label-stripped
            .tab-content
              - if flash[:error].present?
                .alert.alert-danger.display-show
                  %button.close{"data-close" => "alert"}
                  %span
                    = flash[:error]
              - if flash[:notice].present?
                .alert.alert-success.display-show
                  %button.close{"data-close" => "alert"}
                  %span
                    = flash[:notice]

              .form-body
                %div.form-group.col-md-12
                  %div.row.row-bordered.col-md-12.hidden-xs.hidden-sm
                    %div.text-center.col-md-1
                      %b ID
                    %div.text-center.col-md-2
                      %b Avatar
                    %div.text-center.col-md-2
                      %b Name
                    %div.text-center.col-md-2
                      %b Email
                    %div.text-center.col-md-2
                      %b Role
                    %div.text-center.col-md-3
                      %b Action
                  - @users.each do |user|
                    %div.row.row-bordered.col-md-12
                      %div.text-center.col-md-1
                        #{user.id}
                      %div.text-center.col-md-2
                        = image_tag user.get_avatar_path, class: "img-responsive", alt: "", style: "width: 100px; margin: 0 auto;"
                      %div.text-center.col-md-2
                        #{user.name}
                      %div.text-center.col-md-2
                        #{user.email}
                      %div.text-center.col-md-2
                        - if user == current_user
                          #{user.role}
                        - else
                          = form_for(user, url: {:action => 'update_role', :id => user.id}, method: 'post') do |f|
                            =f.select(:role, User.roles.keys.map {|role| [role.titleize, role]},{}, {class: 'form-control select2_category', style: 'margin-bottom: 10px'})
                            =f.submit 'Change Role', :class => 'btn btn-sm green', :style => 'margin: 5px 0'
                      %div.text-center.col-md-3
                        = link_to "Edit User", edit_user_path(user), class: "btn btn-sm green", style: 'margin-bottom: 5px'
                        = link_to('Delete user', user_path(user), :data => {:confirm => 'Hey gurus ! Are you sure ?'}, :method => :delete, :class => 'btn btn-sm btn-danger', style: 'margin-bottom: 5px') unless user == current_user

app/views/users/new.html.haml
%div.page-content-wrapper
  %div.page-content
    %h3.page-title
      User management
    %div.row
      %div.col-md-12
        .panel
          .panel-heading
            New User
          .panel-body
            = render "sign_up_form"
      = "New User"
    .row
      .col-md-12
        .profile-content
          .row
            .col-md-12
              .portlet.light
                .portlet-title.tabbable-line
                  .caption.caption-md
                    %i.icon-globe.theme-font.hide
                    %span.caption-subject.font-blue-madison.bold.uppercase Profile Account
                  %ul.nav.nav-tabs
                    %li.active
                      %a{"data-toggle" => "tab", :href => "#tab_1_3"} New User
                .portlet-body
                  .tab-content
                    - if flash[:error].present?
                      .alert.alert-danger.display-show
                        %button.close{"data-close" => "alert"}
                        %span
                          = flash[:error]
                    - if flash[:notice].present?
                      .alert.alert-success.display-show
                        %button.close{"data-close" => "alert"}
                        %span
                          = flash[:notice]
                    #tab_1_3.tab-pane.active
                      = render "sign_up_form"