config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', :locale => /en/ do
    root 'posts#index'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    post 'forgot_password_create', to: 'sessions#forgot_password_create'
    post 'new_password_create', to: 'sessions#new_password_create'
    get 'confirm_email', to: 'users#confirm_email'
    get 'users', to: 'users#index'
    post 'users/update_role/:id', to: 'users#update_role', as: :update_role
    post 'users/', to: 'users#create'
    get '/oauth2callback' => 'events#callback'

    resources :users do
      post   'update_avatar'
      collection do
        get   'profile'
        get   'password'
        post  'update'
        post  'update_profile'
        post  'change_password'
      end
    end

    resources :posts do
      member do
        get 'up', to: 'posts#up'
        get 'down', to: 'posts#down'
      end
      collection do
        post 'update_result'
        get 'new_vote'
        get 'new_randomize'
        get 'votes', to: 'posts#index', defaults: { type: Post::TYPE_VOTE }
        get 'randomizes', to: 'posts#index', defaults: { type: Post::TYPE_RANDOM }
      end
    end

    resources :posts
    resource :events

  end

  # Mobile APIs
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :public do
        post   'auth_code'  => 'session#auth_code'
        post   'api_token'  => 'session#api_token'
        post   'sign_out'   => 'session#sign_out'
      end

      resources :posts do
        get 'up'
        get 'down'
        get 'update_random' => 'posts#update_random'
        collection do
          post 'update_result'
          get 'new_vote'
          get 'new_randomize' => 'posts#update_random'
          get 'votes', to: 'posts#index', defaults: { type: Post::TYPE_VOTE }
          get 'randomizes', to: 'posts#index', defaults: { type: Post::TYPE_RANDOM }
        end
      end
    end

  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  self.inheritance_column = nil
  before_destroy :delete_image_from_s3

  TYPE_RANDOM = 2
  TYPE_VOTE = 1

  validates :content,
            presence: true
  validates :title,
            presence: true
  validates :cat_name,
            presence: true

  scope :groups, -> { where(:group => nil).order(:id => :desc) }
  scope :belongs_to_post, -> (id) { where(:group => id).order(:id => :desc) }
  scope :max_up, -> (parent_id) { where('id = :id OR posts.group = 1',
                                          { id: "#{parent_id}" } )
                                    .order('length(up) DESC')
                                    .first
                                }

  def type_name
    if self.type == TYPE_RANDOM
      'Randomizer'
    else
      'Vote'
    end
  end

  def authorized?(user_id)
    return self.creator_id.to_i == user_id.to_i
  end

  def vote_result_array
    array = {up:[], down:[]}
    if self.up.present?
      array[:up] = self.up.split(',')
    end
    if self.down.present?
      array[:down] = self.down.split(',')
    end
    array
  end

  def randomise_result_array
    array = []
    if self.result.present?
      array = self.result.split(',')
    end
    array
  end

  def have_children?
    children = Post.where(:group => self.id)
    return children.present?? children : false
  end

  def is_children?
    self.group.present?
  end

  def self.create_random_result(number_taken, total)
    shuffle_array = (0..total-1).to_a.shuffle
    shuffle_array.first(number_taken)
  end

  def self.get_groups
    groups = { "None" => [["None", ""]]}
    Post.groups.where(:type => TYPE_VOTE).group_by { |post| post[:cat_name] }.each do |category|
      name = category[0]
      groups[name] = []
      category[1].each do |post|
        groups[name] << [post.title, post.id]
      end
    end
    groups
  end

  private
    def delete_image_from_s3
      if self.image_url.present?
        s3 = FileStore.bucket
        obj = s3.object(self.image_url)
        obj.delete
      end
    end

end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApiController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # getting all posts
  def index
    type = params[:type]
    if type.present?
      @posts = Post.where(:type => type, :group => nil)
    else
      @posts = Post.where(:creator_id => current_user.id, :group => nil)
    end

    @posts.order!(id: :desc)
    render json: @posts
  end

  # creating new posts
  def create
    @post = Post.new(post_params)
    @post.creator_id = current_user.id

    if @post.save!
      if params[:post][:image_url].present?
        if !(image_url = upload_image_to_s3)
          render json: {error: 'Upload image fail!'}
        else
          @post.update(:image_url => image_url)
        end
      end
      render json: {success: 'Create Post successfully'}
    else
      render json: {fail: "Create post unsuccessfully"}
    end
  end

  def update
    if @post.update(post_params)
      if params[:post][:image_url].present?
        image_url = upload_image_to_s3
        if !image_url
          flash.now[:notice] = init_message(:error, 'Upload image fail!')
        else
          @post.update(:image_url => image_url)
        end
      end

      if @post.type == Post::TYPE_RANDOM
        render json: {success: 'Update Randomise successfully!'}
      else
        render json: {success: 'Update Vote successfully!'}
      end
    end
  end

  def destroy
    @post.destroy
    if @post.is_children?
      redirect_to post_path(@post.group), notice: init_message(:success, 'A child post is deleted successfully!')
    elsif @post.have_children?
      Post.destroy_all(:group => @post.id)
      render json: {success: 'All posts are deleted successfully!'}
    else
      render json: {success: 'A post is deleted successfully!'}
    end
  end

  def up
    @post = Post.find_by(id: params[:post_id])
    render json:{success: false, message: "Random not found"} if @post.nil?
    if not_vote_yet?
      appended_value = [@post.up.to_s, current_user.id].delete_if(&:blank?).join(',')
      @post.update_column(:up, appended_value)
      render json: {success: true}
    else
      render json: {success: false, message: "already voted"}
    end
  end

  def down
    @post = Post.find_by(id: params[:post_id])
    if not_vote_yet?
      appended_value = [@post.down.to_s, current_user.id].delete_if(&:blank?).join(',')
      @post.update_column(:down, appended_value)
      render json: {success: true}
    else
      render json: {success: false, message: "already voted"}
    end
  end

  def update_random
    @post = Post.find_by(id: params[:post_id])
    @users = User.all.shuffle
    res = Post.creat_random_result(@post[:number], @users.count)
    @post.result = res.join(",")
    if @post.save!
      render json: {success: true}
    else
      render json: {success: false}
    end
  end

  def update_result
    @post.update({:result => params[:result].join(","),
                  :status => 1
                 })
    render json: {url: posts_path}
  end

  private
  def not_vote_yet?
    voted_user_ids = @post.vote_result_array[:up] + @post.vote_result_array[:down]
    return !(voted_user_ids.include? current_user.id.to_s)
  end

  def upload_image_to_s3
    image_url = FileStore.random_file_path(ENV['AWS_S3_POST_DIR'], File.extname(params[:post][:image_url].original_filename))
    s3 = FileStore.bucket
    obj = s3.object(image_url)
    if !obj.upload_file(File.expand_path(params[:post][:image_url].tempfile), acl: 'public-read')
      flash.now[:notice] = init_message(:error, 'Cannot upload image')
      return false
    end

    return image_url
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def set_ajax
      @post = Post.find(params[:id])
      @ajax_message = {}
    end

    def post_params
      params.require(:post).permit(:id, :group, :cat_name, :title, :content, :up, :down, :creator_id, :result, :number, :type)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_ajax, only: [:up, :down, :update_result]
  before_action :check_creator_before_edit, only: [:edit, :update, :destroy]

  def index
    type = params[:type]
    if type.present?
      @posts = Post.where(:type => type, :group => nil)
    else
      @posts = Post.where(:creator_id => current_user.id, :group => nil)
    end

    @posts.order!(id: :desc)
    @title = get_title type
    @users = User.all
  end

  def new_vote
    @post = Post.new(:type => Post::TYPE_VOTE)
  end

  def new_randomize
    @post = Post.new(:type => Post::TYPE_RANDOM)
  end

  def create
    @post = Post.new(post_params)
    @post.creator_id = current_user.id

    if @post.save
      if params[:post][:image_url].present?
        if !(image_url = upload_image_to_s3)
          redirect_to list_path, notice: init_message(:error, 'Upload image fail!')
        else
          @post.update(:image_url => image_url)
        end
      end
      redirect_to post_path(@post), notice: init_message(:success, 'Create Post successfully')
    else
      redirect_to posts_path, notice: init_message(:error, 'Create Post fail!')
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      if params[:post][:image_url].present?
        image_url = upload_image_to_s3
        if !image_url
          flash.now[:notice] = init_message(:error, 'Upload image fail!')
        else
          @post.update(:image_url => image_url)
        end
      end

      if @post.type == Post::TYPE_RANDOM
        redirect_to randomizes_posts_path, notice: init_message(:success, 'Update Randomise successfully!')
      else
        redirect_to votes_posts_path, notice: init_message(:success, 'Update Vote successfully!')
      end
    end
  end

  def destroy
    @post.destroy
    if @post.is_children?
      redirect_to post_path(@post.group), notice: init_message(:success, 'A child post is deleted successfully!')
    elsif @post.have_children?
      Post.destroy_all(:group => @post.id)
      redirect_to posts_path, notice: init_message(:success, 'All posts are deleted successfully!')
    else
      redirect_to posts_path, notice: init_message(:success, 'A post is deleted successfully!')
    end
  end

  def show
    if @post.type == Post::TYPE_RANDOM
      show_randomizer_page
    else
      show_vote_page
    end
  end

  def up
    if not_vote_yet?
      appended_value = [@post.up.to_s, current_user.id].delete_if(&:blank?).join(',')
      @post.update_column(:up, appended_value)
      @ajax_message[:success] = 'Thank you! You voted UP!'
    else
      @ajax_message[:error] = 'Hey! You\'ve already voted dude!'
    end
  end

  def down
    if not_vote_yet?
      appended_value = [@post.down.to_s, current_user.id].delete_if(&:blank?).join(',')
      @post.update_column(:down, appended_value)
      @ajax_message[:success] = 'Thank you! You voted DOWN!'
    else
      @ajax_message[:error] = 'Hey! You\'ve already voted dude!'
    end
  end


  def update_result
    @post.update({:result => params[:result].join(","),
                 :status => 1
                })
    render json: {url: posts_path}
  end

  private
    def not_vote_yet?
      voted_user_ids = @post.vote_result_array[:up] + @post.vote_result_array[:down]
      return ! (voted_user_ids.include? current_user.id.to_s)
    end

    def upload_image_to_s3
      image_url = FileStore.random_file_path(ENV['AWS_S3_POST_DIR'], File.extname(params[:post][:image_url].original_filename))
      s3 = FileStore.bucket
      obj = s3.object(image_url)
      if !obj.upload_file(File.expand_path(params[:post][:image_url].tempfile), acl:'public-read')
        flash.now[:notice] = init_message(:error, 'Cannot upload image')
        return false
      end

      return image_url
    end

    def show_vote_page
      @children = Post.belongs_to_post(@post.id)
      render 'show_vote'
    end

    def show_randomizer_page
      @users = User.all.shuffle
      res = @post.result.nil? ? Post.create_random_result(@post[:number], @users.count) : [@post.result]
      @post.result = res.join(",")
      @post.save!
      @view_params = {
          result: res       
      }
      render 'show_randomizer'
    end

    def edit_vote_group_page
      render 'edit_vote_group'
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def set_ajax
      @post = Post.find(params[:id])
      @ajax_message = {}
    end

    def post_params
      params.require(:post).permit(:id, :group, :cat_name, :title, :content, :up, :down, :creator_id, :result, :number, :type)
    end

    def get_title(type)
      case type
        when Post::TYPE_VOTE
          'Votes'
        when Post::TYPE_RANDOM
          'Randomizes'
        else
          'Your posts'
      end
    end

    def check_creator_before_edit
      creator_id = @post.creator_id
      current_user_id = current_user.id

      if creator_id.to_s != current_user_id.to_s
        redirect_to posts_path
      end
    end

end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_display_vote.haml
%div.row
  %div.col-sm-6{ :style => 'width: 40%' }
    - if post.image_url.present?
      %img.img-rounded.img-responsive{ :src => FileStore.public_url(post.image_url), :width => '100%'}
    - else
      %div.no_image
  %div.col-sm-6{ :style => 'width: 60%' }
    .panel.panel-info{'data-id': post.id}
      .panel-heading.vote_control
        %div.message
        =link_to up_post_path(post), remote: true, class: 'btn btn-outline btn-circle btn-lg blue' do
          %i.glyphicon.glyphicon-thumbs-up
          %span
            =post.up.present?? post.up.split(',').count() : 0
        =link_to down_post_path(post) ,remote: true, class: 'btn btn-outline btn-circle btn-lg red' do
          %i.glyphicon.glyphicon-thumbs-down
          %span
            =post.down.present?? post.down.split(',').count() : 0
      .panel-body
        %div.result.blue
          %i.glyphicon.glyphicon-thumbs-up.up
          - if post.vote_result_array[:up].present?
            - post.vote_result_array[:up].each do |id|
              %div.user{style: "background: url(" + User.get_avatar_path_by_id(id) + ")"}
        %div.result.red
          %i.glyphicon.glyphicon-thumbs-down.down
          - if post.vote_result_array[:down].present?
            - post.vote_result_array[:down].each do |id|
              %div.user{style: "background: url(" + User.get_avatar_path_by_id(id) + ")"}
        %div.content
          = simple_format post.content

app/views/posts/_form.html.haml
=form_for @guideline_rate, html: {class: 'form-horizontal form-bordered form-label-stripped'} do |f|
  .form-body
    .form-group
      %label.control-label.col-md-3 Origin Location
      .col-md-9
        = f.select :origin_location_id, Location.order(name: :asc).pluck(:name, :id), {}, {class: 'form-control select2_category'}
    .form-group
      %label.control-label.col-md-3 Destination Location
      .col-md-9
        = f.select :destination_location_id, Location.order(name: :asc).pluck(:name, :id), {}, {class: 'form-control select2_category'}
    .form-group
      %label.control-label.col-md-3 Type Size
      .col-md-9
        = f.select :type_size_id, TypeSize.order(name: :asc).pluck(:name, :id), {}, {class: 'form-control select2_category'}
    .form-group.last
      %label.control-label.col-md-3 Rate
      .col-md-9
        = f.text_field :rate, class: 'form-control', placeholder: 'Rate', type: 'number'
        %span.help-block Rate for type size
  .form-actions
    .row
      .col-md-offset-3.col-md-9
        %button.btn.green{:type => 'submit'}
          %i.fa.fa-check
          Submit
        = link_to 'Cancel', guideline_rates_path, class: 'btn default'

app/views/posts/_randomize.html.haml
= form_for @post, html: {class: 'form-horizontal form-bordered form-label-stripped'} do |f|
  .form-body
    %div.form-group
      %label.control-label.col-md-3
        Category:
      .col-md-9
        = f.select :cat_name, ['Party', 'Cinema', 'Team Building', 'Massage', 'Other'], {}, {class: 'form-control select2_category'}
    %div.form-group
      %label.control-label.col-md-3
        Title:
      .col-md-9
        = f.text_field :title, placeholder: 'What...', class: 'form-control'
    %div.form-group
      %label.control-label.col-md-3
        Content:
      .col-md-9
        = f.text_area :content, placeholder: 'When...', rows: 18, class: 'form-control'
    %div.form-group
      %label.control-label.col-md-3
        Photo:
      .col-md-9
        = f.file_field :image_url, multipart: true
    %div.form-group
      %label.control-label.col-md-3
        Randomize time:
      .col-md-9
        = f.select :number, [1,2,3,4,5], {}, {class: 'form-control select2_category'}

    = f.hidden_field :type
  .form-actions
    .row
      .col-md-offset-3.col-md-9
        %button.btn.green{:type => 'submit'}
          Submit
        = link_to 'Cancel', posts_path(type: 'randomize'), class: 'btn default'

app/views/posts/_vote.html.haml
= form_for @post, html: {class: 'form-horizontal form-bordered form-label-stripped'} do |f|
  .form-body
    %div.form-group
      %label.control-label.col-md-3
        Group with:
      .col-md-9
        = f.select :group, Post.get_groups, {}, {class: 'form-control select2_category'}
    %div.form-group
      %label.control-label.col-md-3
        Category:
      .col-md-9
        = f.select :cat_name, ['Party', 'Cinema', 'Team Building', 'Massage', 'Other'], {}, {class: 'form-control select2_category'}
    %div.form-group
      %label.control-label.col-md-3
        Title:
      .col-md-9
        = f.text_field :title, placeholder: 'What...', class: 'form-control'
    %div.form-group
      %label.control-label.col-md-3
        Content:
      .col-md-9
        = f.text_area :content, placeholder: 'When...', class: 'form-control'
    %div.form-group
      %label.control-label.col-md-3
        Photo:
      .col-md-9
        = f.file_field :image_url, multipart: true
    = f.hidden_field :type
  .form-actions
    .row
      .col-md-offset-3.col-md-9
        %button.btn.green{:type => 'submit'}
          Submit
        = link_to 'Cancel', posts_path(type: 'vote'), class: 'btn default'

app/views/posts/down.js.erb
$panel = $('.panel[data-id="<%= @post.id %>"]')
<% if @ajax_message[:success].present? %>
  $panel.find('.btn.red span').text("<%= @post.down.split(',').count() %>")

  $user_div = $('<div class="user" style="background: url(' + <%= current_user.get_avatar_path %> + ')"></div>')
  $user_div.css({opacity:0});
  $panel.find('.panel-body .result.red').append($user_div.animate({opacity:1}, 'slow'))

  $panel.find('.message').addClass('success').html('<%= @ajax_message[:success] %>').show().delay(2000).fadeOut('fast')
<% else %>
  $panel.find('.message').addClass('error').html('<%= @ajax_message[:error] %>').show().delay(2000).fadeOut('fast')
<% end %>

app/views/posts/edit.html.haml
%div.page-content-wrapper
  %div.page-content
    %h3.page-title
      We are Gurus. We play hard, code harder
    %div.row
      %div.col-md-12
        %div.portlet.light
          %div.portlet-title
            %div.caption
              %i.icon-social-dribbble.font-green
              %span.caption-subject.font-green.bold.uppercase
                = "Update #{@post.type_name}"
          .portlet-body.form
            = form_for @post, html: {class: 'form-horizontal form-bordered form-label-stripped'} do |f|
              .form-body
                %div.form-group
                  %label.control-label.col-md-3
                    Category:
                  .col-md-9
                    = f.select :cat_name, ['Party', 'Cinema', 'Team Building', 'Massage', 'Other'], {}, {class: 'form-control select2_category'}
                %div.form-group
                  %label.control-label.col-md-3
                    Title:
                  .col-md-9
                    = f.text_field :title, placeholder: 'What...', class: 'form-control'
                %div.form-group
                  %label.control-label.col-md-3
                    Content:
                  .col-md-9
                    = f.text_area :content, placeholder: 'When...', class: 'form-control', rows: 10
                - if @post.type == Post::TYPE_RANDOM
                  %div.form-group
                    %label.control-label.col-md-3
                      Number of selections
                    .col-md-9
                      = f.select :number, [1,2,3,4,5], {}, class: 'form-control select2_category'
                %div.form-group
                  %label.control-label.col-md-3
                    Photo:
                  .col-md-9
                    = f.file_field :image_url, multipart: true
                = f.hidden_field :type
              .form-actions
                .row
                  .col-md-offset-3.col-md-9
                    %button.btn.green{:type => 'submit'}
                      Submit
                    - if @post.type == Post::TYPE_RANDOM
                      = link_to 'Cancel', randomizes_posts_path, class: 'btn default'
                    - else
                      = link_to 'Cancel', votes_posts_url, class: 'btn default'

app/views/posts/index.html.haml
%div.page-content-wrapper
  %div.page-content
    %h3.page-title
      We are Gurus. We play hard, code harder
    %div.row
      %div.col-md-12
        %div.portlet.light
          %div.portlet-title
            %div.caption
              %i.icon-social-dribbble.font-green
              %span.caption-subject.font-green.bold.uppercase
                = @title
          .portlet-body.form
            - @posts.each do |post|
              - children = post.have_children?
              %div{class: "mt-element-ribbon bg-grey-steel post type_#{post.type}",
                style: "background-image: url(#{FileStore.public_url(post.image_url)}) !important",
                'data-url': "#{post_path(post.id)}"}
                %div.header
                  %div{class: "category ribbon ribbon-color-default uppercase"}
                    = "#{post.cat_name}" + (children ? " (#{children.count+1})" : "")
                  %div.control
                    - if post.authorized? current_user.id
                      - if post.creator_id.to_s == current_user.id.to_s
                        %a{href: edit_post_path(post)}
                          Edit
                        |
                        %a.delete{data: {toggle: 'modal', target: '#confirm-delete', href: post_path(post)}}
                          Delete
                %div.space
                %div.text
                  %div.title
                    = post.title
                  -#%div.content
                  -#  = post.content
                %div.footer
                  -if post.type == 1
                    - if children
                      - post_with_highest_up = Post.max_up(post.id)
                      - count_up = post_with_highest_up.vote_result_array[:up].length
                      - count_down = post_with_highest_up.vote_result_array[:down].length
                    - else
                      - count_up = post.vote_result_array[:up].length
                      - count_down = post.vote_result_array[:down].length
                    %div.up
                      %div.number
                        = count_up
                      Up
                    %div.down
                      %div.number
                        = count_down
                      Down
                    %div.unknown
                      %div.number
                        = @users.count - (count_up + count_down)
                      Unknown
                  - else
                    - post.randomise_result_array.each do |user_id|
                      %div.user{style: "background: url(/images/avatars/" + user_id + ".jpg)"}

:javascript
  $(document).ready(function() {
    $('.post .space, .post .text').click(function() {
      window.location = $(this).parents('.post').data('url')
    })
  })

app/views/posts/my_posts.html.haml
%h1 Dashboard
- @posts.each do |post|
  %div{class: "mt-element-ribbon bg-grey-steel post type_#{post.type}", style: "background-image: url(../images/#{post.image_url}) !important", 'data-id': "#{post.id}"}
    %div.header
      %div{class: "category ribbon ribbon-color-default uppercase"}
        = post.cat_name
      %div.control
        %a
          Edit
        |
        %a
          Delete
    %div.space
    %div.text
      %div.title
        = post.title
      %div.content
        = post.content
    %div.footer
      -if post.type == 1
        %div.up
          %div.number
            = post.up
          Up
        %div.down
          %div.number
            = post.down
          Down
        %div.unknown
          %div.number
            = @users_count
          Unknown
      - else
        %div.user

:javascript
  $(document).ready(function() {
    $('.post').click(function() {
      window.location = 'posts/' + $(this).data('id')
    })

    $('.post a').click(function(e) {
      e.preventDefault();
      e.stopPropagation();
    })
  })

app/views/posts/new_randomize.html.haml
%div.page-content-wrapper
  %div.page-content
    %h3.page-title
      New Post
      %small for randomize
    %div.row
      %div.col-md-12
        %div.portlet.light
          %div.portlet-title
            %div.caption
              %i.icon-social-dribbble.font-green
              %span.caption-subject.font-green.bold.uppercase
                Create new randomise
          .portlet-body.form
            = render 'randomize'

app/views/posts/randomizes.html.haml
%h1 Dashboard
- @posts.each do |post|
  %div{class: "mt-element-ribbon bg-grey-steel post type_#{post.type}", style: "background-image: url(../images/#{post.image_url}) !important", 'data-id': "#{post.id}"}
    %div.header
      %div{class: "category ribbon ribbon-color-default uppercase"}
        = post.cat_name
      %div.control
        %a
          Edit
        |
        %a
          Delete
    %div.space
    %div.text
      %div.title
        = post.title
      %div.content
        = post.content
    %div.footer
      -if post.type == 1
        %div.up
          %div.number
            = post.up
          Up
        %div.down
          %div.number
            = post.down
          Down
        %div.unknown
          %div.number
            = @users_count
          Unknown
      - else
        %div.user

:javascript
  $(document).ready(function() {
    $('.post').click(function() {
      window.location = 'posts/' + $(this).data('id')
    })

    $('.post a').click(function(e) {
      e.preventDefault();
      e.stopPropagation();
    })
  })

app/views/posts/show_randomizer.html.haml
%div.page-content-wrapper
  %div.page-content
    %h3.page-title
      = @post.type_name
    %div.row
      %div.col-md-12
        %div.portlet.light
          %div.portlet-title
            %div.caption
              %i.icon-social-dribbble.font-green
              %span.caption-subject.font-green.bold.uppercase
                = @post.cat_name + " | " + @post.title
          .portlet-body.form
            %p
              %img.img-rounded.img-responsive{ :src => FileStore.public_url(@post.image_url)}
            %p
              = "Number of selection: #{@post.number}"
            %p
              = simple_format @post.content
            %div.container
              - @users.each do |user|
                %div.user{style: "background:url('#{user.get_avatar_path}')", 'data-user_id': user.id, 'data-selected': (@post.randomise_result_array.include? user.id.to_s).to_s}
                  %div.remove-user{style: "cursor:pointer"}
                    x
                  %div.placeholder
                  %div.name
                    #{user.name}
            %div.container
              - if @post.status == 0
                %button.btn.green.submit.start
                  Start
              - if @post.status == 1
                %button.btn.green.submit.start{disabled: true}
                  DONE

-#POST IS ALREAY COMPLETED
- if @post.status == 1
  :javascript
    $(document).ready( function() {
      $('.user[data-selected=true]').each( function() {
        $(this).find('.placeholder').append('<div class="boob">')
      })
    })

-#POST IS NEW
- if @post.status == 0
  :javascript
    var number_of_pointers = #{@post[:number]}
    var result = #{@view_params[:result]}
    var post_id = #{@post[:id]}


  :javascript
    $(document).ready(function() {
      var nUsers = $('.user').length

      $('.remove-user').click(function () {
        $(this).parent().remove()
        nUsers--
      })

      $('button.submit').click( function() {
        if( $(this).hasClass('start') ) {
          startRandomise()
        } else if( $(this).hasClass('finish') ) {
          completeRandomise()
        }
      })

      function completeRandomise() {
        chosen_user_id = getChosenUserId()
        $.ajax({
          method: "POST",
          url: 'update_result',
          data: {result: chosen_user_id, id: post_id},
        }).done(function(data) {
          window.location = data.url
        })
      }

      function startRandomise() {
        $button = $('button.submit')
        $button.attr( {'disabled': true} )
        $button.text('Running...')

        for(i=0;i<number_of_pointers;i++)
          runPointer(i)
      }

      function getChosenUserId() {
        var ids = []
        $('.user .placeholder .boob').each(function() {
          ids.push($(this).parents('.user').data('user_id'))
        })
        return ids
      }

      function runPointer(index) {
        var time = 5000
        var step = 500
        var randomInterval = setInterval( function () {
          var newPosition = getRandomNumber(nUsers)
          movePointer(index, newPosition)
          time -= step
          // Setup new position
          result[index] = newPosition
          if(time <= 0) {
            clearInterval(randomInterval)

            //this will be executed number of times which is set by number_of_pointers
            //but its temporarily OK for now
            $('button.submit').attr( {'class': 'btn red submit finish', 'disabled': false} )
            $('button.submit').text('Finish')
          }
        }, step)
      }

      function getRandomNumber(max) {
        return Math.round(Math.random() * (max - 1))
      }

      function movePointer(index, position) {
        $('.user').find('.boob.number_' + index).remove()
        $('.user').eq(position).find('.placeholder').append('<div class="boob number_' +  index +'"></div>')
      }
    })

app/views/posts/show_vote.html.haml
%div.page-content-wrapper
  %div.page-content
    %h3.page-title
      = @post.type_name
    %div.row
      %div.col-md-12
        %div.portlet.light
          %div.portlet-title
            %div.caption
              %i.icon-social-dribbble.font-green
              %span.caption-subject.font-green.bold.uppercase
                = @post.cat_name + " | " + @post.title
          = render "display_vote", :post => @post
          - @children.each do |child|
            %div.row
              %p
                - if child.authorized? current_user.id
                  %div{style: 'text-align: right'}
                    %a.delete{data: {toggle: 'modal', target: '#confirm-delete', href: post_path(child)}}
                      Remove
            = render "display_vote", :post => child
          %div.portlet-body.flip-scroll