config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', :locale => /en/ do
    root 'posts#index'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    post 'forgot_password_create', to: 'sessions#forgot_password_create'
    post 'new_password_create', to: 'sessions#new_password_create'
    get 'confirm_email', to: 'users#confirm_email'
    get 'users', to: 'users#index'
    post 'users/update_role/:id', to: 'users#update_role', as: :update_role
    post 'users/', to: 'users#create'
    get '/oauth2callback' => 'events#callback'

    resources :users do
      post   'update_avatar'
      collection do
        get   'profile'
        get   'password'
        post  'update'
        post  'update_profile'
        post  'change_password'
      end
    end

    resources :posts do
      member do
        get 'up', to: 'posts#up'
        get 'down', to: 'posts#down'
      end
      collection do
        post 'update_result'
        get 'new_vote'
        get 'new_randomize'
        get 'votes', to: 'posts#index', defaults: { type: Post::TYPE_VOTE }
        get 'randomizes', to: 'posts#index', defaults: { type: Post::TYPE_RANDOM }
      end
    end

    resources :posts
    resource :events

  end

  # Mobile APIs
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :public do
        post   'auth_code'  => 'session#auth_code'
        post   'api_token'  => 'session#api_token'
        post   'sign_out'   => 'session#sign_out'
      end

      resources :posts do
        get 'up'
        get 'down'
        get 'update_random' => 'posts#update_random'
        collection do
          post 'update_result'
          get 'new_vote'
          get 'new_randomize' => 'posts#update_random'
          get 'votes', to: 'posts#index', defaults: { type: Post::TYPE_VOTE }
          get 'randomizes', to: 'posts#index', defaults: { type: Post::TYPE_RANDOM }
        end
      end
    end

  end
end

app/views/layouts/_confirm_delete.html.haml
#confirm-delete.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'confirmDeleteLabel', :role => 'dialog', :tabindex => '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'modal', :type => 'button'} ×
        %h4#confirmDeleteLabel.modal-title Confirm Delete
      .modal-body
        %p Are you sure, Do you want to delete this record?
      .modal-footer
        %form#form-delete{method: :post}
          = hidden_field_tag 'authenticity_token', form_authenticity_token
          = hidden_field_tag '_method', 'delete'
          %button.btn.btn-default{'data-dismiss' => 'modal', :type => 'button'} Cancel
          %button.btn.btn-danger.btn-ok{type: 'submit'} Delete

app/views/layouts/_flash_messages.html.haml
%div
  - flash.each do |key, value|
    %div{:class => "#{flash_class(key)} fade in", :style => "text-align:center;"}
      %a.close{"data-dismiss" => "alert", :href => "#", color: "#000000;"} ×
      = value

app/views/layouts/_footer.html.haml
%div.page-footer
  %div.page-footer-inner
  %div.scroll-to-top{:style => "display: none;"}
    %i.icon-arrow-up

app/views/layouts/_header.html.haml
%div.page-header.navbar.navbar-fixed-top
  %div.page-header-inner
    %div.page-logo
      = link_to posts_path do
        %img.logo-default{:alt => "logo", :src => "/images/team_logo.png"}
      %div.menu-toggler.sidebar-toggler
    %a.menu-toggler.responsive-toggler{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :href => "javascript:;"}
    %div.page-top
      %div.top-menu
        %ul.nav.navbar-nav.pull-right
          %li.dropdown.dropdown-user
            %a.dropdown-toggle{"data-close-others" => "true", "data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "javascript:;"}
              %span.username= current_user.name
              %i.fa.fa-angle-down
            %ul.dropdown-menu.dropdown-menu-default
              %li
                = link_to edit_user_path(current_user.id) do
                  %i.icon-user
                  My Profile
              %li
                = link_to logout_path, method: :delete do
                  %i.icon-key
                  Log Out

app/views/layouts/_sidebar.html.haml
%div.page-sidebar-wrapper
  %div.page-sidebar.navbar-collapse.collapse
    %ul.page-sidebar-menu.page-header-fixed.page-sidebar-menu-hover-submenu{"data-auto-scroll" => "true", "data-keep-expanded" => "false", "data-slide-speed" => "200"}
      %li.nav-item.start.active.open
        = link_to posts_path, class: 'nav-link' do
          %i.icon-social-dribbble
          %span.title My Posts
          %span.selected
          %span.arrow.open
        %ul.sub-menu
          %li.nav-item
            = link_to new_vote_posts_path, class: 'nav-link' do
              %span.title New Vote
          %li.nav-item
            = link_to new_randomize_posts_path, class: 'nav-link' do
              %span.title New Randomise
      %li.nav-item
        = link_to votes_posts_path, class: 'nav-link' do
          %i.icon-bar-chart
          %span.title Vote
      %li.nav-item
        = link_to randomizes_posts_path, class: 'nav-link' do
          %i.icon-layers
          %span.title Randomizer
          %span.arrow
      %li.nav-item
        - if policy(@current_user).index?
          = link_to users_path, class: 'nav-link' do
            %i.icon-users
            %span.title Users
            %span.arrow
      %li.nav-item
        = link_to events_path, class: 'nav-link' do
          %i.icon-calendar
          %span.title Events
          %span.arrow

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title Symphony | Auto Pricing System
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = csrf_meta_tag
    = stylesheet_link_tag 'application', media: 'all', data: {'turbolinks-track' => true}
    = javascript_include_tag 'application', data: {'turbolinks-track' => true}
  %body.page-header-fixed.page-sidebar-closed-hide-logo.page-container-bg-solid
    = render 'layouts/header'
    %div.page-container
      = render 'layouts/sidebar'
      = yield
    = render 'layouts/footer'
    = render 'layouts/confirm_delete'

:javascript
  var notice = '#{flash[:notice].present?? flash[:notice] : ""}';

  $('.select2_category').select2({
    theme: "classic"
  });